#!/bin/bash

sqlite3 website.db "DROP TABLE bookType;"
sqlite3 website.db "DROP TABLE books;"

sqlite3 website.db "CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, author TEXT, description TEXT, image TEXT);"
sqlite3 website.db "CREATE TABLE IF NOT EXISTS bookType (id INTEGER PRIMARY KEY AUTOINCREMENT, book_id INTEGER NOT NULL, price_mu INTEGER, ean TEXT, type TEXT, condition TEXT, qty INTEGER, weight_gm INTEGER, FOREIGN KEY (book_id) REFERENCES books (id));"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('The Merchant of Venice','William Shakespeare','This early work of Shakespeare is considered to be the finest and most thought-provoking of all comedies of his time. Being so, it carries the universal theme of good triumphing over evil,as it depicts the interplay of vengeance and shrewdness.', 'merchant_of_venice.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(1, 860, '978-9380816296', 'paperback', 'new', 25, 154);"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(1, 1020, '978-9380812458', 'hardcover', 'new', 15, 310);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('Julius Caesar','William Shakespeare','Julius Caesar is a key link between Shakespeare’s histories and his tragedies. Unlike the Caesar drawn by Plutarch in a source text, Shakespeare’s Caesar is surprisingly modern: vulnerable and imperfect, a powerful man who does not always know himself. The open-ended structure of the play insists that revealing events will continue after the play ends, making the significance of the history we have just witnessed impossible to determine in the play itself. John D. Cox’s introduction discusses issues of genre, characterization, and rhetoric, while also providing a detailed history of criticism of the play. Appendices provide excerpts from important related works by Lucretius, Plutarch, and Montaigne.', 'julius_caesar.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(2, 132, '978-8129101914', 'paperback', 'new', 12, 75);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('Othello','William Shakespeare','“I would not put a thief in my mouth to steal my brains.” A fatal tale of love, jealousy and betrayal, the play revolves around, Othello, a general in Venetian army and Iago, his ensign. Othello traverses through a series of unfortunate events from Iago’s plotting, the misinterpreted image of Desdemona, Othello’s fatal error and his end as a tragic hero! Twisting its way through manipulations and bloodsheds, the story creates a sense of awe and fear in the readers.Considered as the most powerful and moving of Shakespeare’s great tragedies, Othello has enjoyed popularity among the readers from the Jacobean period to the present day.', 'othello.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(3, 104, '978-9380816302', 'paperback', 'new', 65, 204);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('Turn Left at Orion','Guy Consolmagno','With over 150,000 copies sold since its first publication, this is one of the most popular astronomy books of all time. This unique guidebook to the night sky shows you how to observe a host of celestial wonders. Its distinct format of object-by-object spreads illustrates how deep-sky objects and planets actually look through a small telescope, while its large pages and spiral binding allow for use outside. Along with updated star names and astronomical information, this new edition provides links to a dedicated webpage with up-to-date tables and images, and an improved planets chapter.', 'turn_left_at_orion.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(4, 2500, '978-1108457569', 'hardcover', 'new', 32, 380);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('The Ape that Understood the Universe','Steve Stewart-Williams','The Ape that Understood the Universe is the story of the strangest animal in the world: the human animal. It opens with a question: How would an alien scientist view our species? What would it make of our sex differences, our sexual behavior, our child-rearing patterns, our moral codes, our religions, our languages, and science? The book tackles these issues by drawing on ideas from two major schools of thought: evolutionary psychology and cultural evolutionary theory. The guiding assumption is that humans are animals, and that like all animals, we evolved to pass on our genes. At some point, however, we also evolved the capacity for culture - and from that moment, culture began evolving in its own right. This transformed us from a mere ape into an ape capable of reshaping the planet, travelling to other worlds, and understanding the vast universe of which we’re but a tiny, fleeting fragment.', 'ape_that_understood.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(5, 1999, '978-1108425049', 'paperback', 'new', 65, 235);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('The Bookshop of the Broken Hearted','Robert Hillman','Tom Hope doesn’t chase rainbows. He does his best on the farm - he milks the cows, harvests the apples, looks after the sheep - but Tom’s been lonely since his wife Trudy left, taking little Peter with her to go join the holy rollers.Enter Hannah Babel, quixotic smalltown bookseller: the second Jew - and the most vivid person - Tom has ever met. When she asks him to move in, and help her build Australia’s most beautiful bookshop, Tom dares to believe they could make each other happy. But it is 1968: twenty-four years since Hannah and her own little boy arrived at Auschwitz. Tom Hope is taking on a battle with heartbreak he can barely even begin to imagine.', 'bookshop_of_broken.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(6, 699, '978-0571349784', 'paperback', 'new', 56, 268);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('The Fed and Lehman Brothers','Laurence M. Ball','The bankruptcy of the investment bank Lehman Brothers was the pivotal event of the 2008 financial crisis and the Great Recession that followed. Ever since the bankruptcy, there has been heated debate about why the Federal Reserve did not rescue Lehman in the same way it rescued other financial institutions, such as Bear Stearns and AIG. The Fed’s leaders from that time, especially former Chairman Ben Bernanke, have strongly asserted that they lacked the legal authority to save Lehman because it did not have adequate collateral for the loan it needed to survive. Based on a meticulous four-year study of the Lehman case, The Fed and Lehman Brothers debunks the official narrative of the crisis. It shows that in reality, the Fed could have rescued Lehman but officials chose not to because of political pressures and because they underestimated the damage that the bankruptcy would do to the economy. The compelling story of the Lehman collapse will interest anyone who cares about what caused the financial crisis, whether the leaders of the Federal Reserve have given accurate accounts of their actions, and how the Fed can prevent future financial disasters.', 'fed_and_lehman.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(7, 1709, '978-1108420969', 'hardcover', 'new', 62, 294);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('Fighting the People’s War','Jonathan Fennell','Fighting the People’s War is an unprecedented, panoramic history of the ’citizen armies’ of the United Kingdom, Australia, Canada, India, New Zealand and South Africa, the core of the British and Commonwealth armies in the Second World War. Drawing on new sources to reveal the true wartime experience of the ordinary rank and file, Jonathan Fennell fundamentally challenges our understanding of the War and of the relationship between conflict and socio-political change. He uncovers how fractures on the home front had profound implications for the performance of the British and Commonwealth armies and he traces how soldiers’ political beliefs, many of which emerged as a consequence of their combat experience, proved instrumental to the socio-political changes of the postwar era. Fighting the People’s War transforms our understanding of how the great battles were won and lost as well as how the postwar societies were forged.', 'fighting_the_war.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(8, 2199, '978-1107030954', 'hardcover', 'new', 16, 966);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('Crushed','Kate Hamer','’Mesmerising, compulsive, deliciously dark - and so good on the complex and thorny bond between friends. Kate Hamer’s writing is incandescent.’ Lucy Foley, author of The Hunting Party', 'crushed.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(9, 1055, '978-0571336654', 'hardcover', 'new', 42, 416);"

sqlite3 website.db "INSERT INTO books(name, author, description, image) VALUES('The Cambridge History of Welsh Literature','Geraint Evans','The literature of Wales is one of the oldest continuous literary traditions in Europe. The earliest surviving poetry was forged in the battlefields of post-Roman Wales and the ’Old North’ of Britain, and the Welsh-language poets of today still write within the same poetic tradition. In the early twentieth century, Welsh writers in English outnumbered writers in Welsh for the first time, generating new modes of writing and a crisis of national identity which began to resolve itself at the end of the twentieth century with the political devolution of Wales within the United Kingdom. By considering the two literatures side by side, this book argues that bilingualism is now a normative condition in Wales. Written by leading scholars, this book provides a comprehensive chronological guide to fifteen centuries of Welsh literature and Welsh writing in English against a backdrop of key historical and political events in Britain.', 'cambridge_history_welsh.jpg');"
sqlite3 website.db "INSERT INTO bookType(book_id, price_mu, ean, type, condition, qty, weight_gm) VALUES(10, 8542, '978-1107106765', 'hardcover', 'new', 10, 854);"
